site_name: PEROVSAT Mission Documentation
site_url: https://perovsat.github.io/mission-website/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Documentation:
    - Software:
      - Tutorials:
        - Getting Started: documentation/software/tutorials/getting-started.md
      - How-to Guides: documentation/software/how-to/index.md
      - Reference: documentation/software/reference/index.md
      - Explanation: documentation/software/explanation/index.md
    - Payload: documentation/payload/index.md
    - Electronics: documentation/electronics/index.md
